### ISSUE TITLE
Extract .dmg, .pax/.paxZ, .xar, .pkg and fallback on tar autodetection

### ISSUE THREAD

**Issue by kdeldycke** [romkatv/archive#1]
Just stumbled upon this repository and considering using it. My own take on an `extract()` utility at https://github.com/kdeldycke/dotfiles/blob/23ac0cd2a6c9442420537ca4058ef9e4eeb1b33d/dotfiles/.zshrc#L308-L329 was a quick hack and your version is much cleaner and robust! 👍 

I'd like to point out some differences:
- Extracts `*.dmg` macOS packages by the way of `hdiutil mount "$1"`
- Supports `*.pax` and `*.pax.Z` extraction
- Supports `*.xar` and `*.pkg`

I also found that [GNU's tar has autodetection based on the file extension](https://www.gnu.org/software/tar/manual/html_node/gzip.html#auto_002dcompress), so I re-used it that as a catch-all to make the construct more future proof.

Does these features have a place in your utilities? In which case, what is the best course to have them integrated?

**Comment by romkatv** [comment]
> Does these features have a place in your utilities?

Sure, sounds useful.

> In which case, what is the best course to have them integrated?

Send a PR.
